# WNDWIDTH: 1600
# WNDHEIGHT: 900
WNDWIDTH: 1600
WNDHEIGHT: 900
#FOLDER: grid_map_Traj_test
FOLDER: WulingNew2D
FOLDER2: 
#FOLDER: baoxin
#MODE_0_TRAJ_ODOM,
#MODE_1_GRID_MAP,
#MODE_2_AREA_SLAM,
#MODE_3_AREA_OCCLUSION,
#MODE_4_AREA_CORRIDOR,
#MODE_5_TRAJ_PLANNING
#MODE_6_GRID_COMPARE
MODE: 1

  
